f=open("aylik_masraf.txt", "w+")
aylik_gelir= int(input("Aylik gelirinizi giriniz: "))
mutfak_gideri= int(input("Aylik mutfak masrafinizi giriniz: "))
egitim_masrafi= int(input("Aylik egitim masrafinizi giriniz: "))
giyim_gideri= int(input("Aylik giyim masrafinizi giriniz: "))
ulasim_masrafi= int(input("Aylik ulasim masrafinizi giriniz: "))
aylik_gider =int(mutfak_gideri+egitim_masrafi+giyim_gideri+ulasim_masrafi)
print("Aylik toplam masrafiniz",aylik_gider, "dir.")
print("Aylik gider miktarinizin aylik gelirinize orani:", (aylik_gider)/aylik_gelir, "dir.")

print(aylik_gelir, file=f)
print(mutfak_gideri, file=f)
print(egitim_masrafi, file=f)
print(giyim_gideri, file=f)
print(ulasim_masrafi, file=f)
print("Aylik toplam gideriniz", mutfak_gideri+egitim_masrafi+giyim_gideri+ulasim_masrafi, "dir.", file=f)
print("Aylik gider miktarinizin aylik gelirinze orani:", (mutfak_gideri+egitim_masrafi+giyim_gideri+ulasim_masrafi/aylik_gelir,), file=f)
f.close()
